version: "3.4"
services:
  api:
    profiles: ["dev"]
    build:
      context: ./server
      dockerfile: Dockerfile.local
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    depends_on:
      - flyway
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/postgres?schema=public"
  db:
    image: postgres:latest
    container_name: 5-a-side-organiser_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/postgres -schemas=public -user=user
      -password=password -connectRetries=5 migrate
    volumes:
      - ./database:/flyway/sql
    depends_on:
      - db
volumes:
  db:
    name: 5-a-side-organiser_db
